# Generated by Django 4.1.1 on 2022-09-14 10:56

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('datecreation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('type', models.CharField(choices=[('tank', 'Танки'), ('healer', 'Хилы'), ('DD', 'ДД'), ('merchant', 'Торговцы'), ('gildmaster', 'Гилдмастеры'), ('questgiver', 'Квестгиверы'), ('smith', 'Кузнецы'), ('tanner', 'Кожевники'), ('potionmaker', 'Зельевары'), ('spellmaster', 'Мастера заклинаний')], default='merchant', max_length=16, verbose_name='Тип обьявления')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Сообщение')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameBoard.post')),
            ],
        ),
    ]
